# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(default='Anonymous', max_length=30)),
                ('date_pub', models.DateTimeField()),
                ('post_number', models.IntegerField(default=1)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PostCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.IntegerField(default=0)),
                ('threads_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thread', models.CharField(max_length=30)),
                ('name_author', models.CharField(default='Anonymous', max_length=30)),
                ('date_pub', models.DateTimeField()),
                ('last_date_pub', models.DateTimeField()),
                ('original_post_number', models.IntegerField(default=1)),
                ('thread_posts_number', models.IntegerField(default=0)),
                ('original_post', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.Section')),
            ],
        ),
        migrations.AddField(
            model_name='postcounter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.Thread'),
        ),
    ]
